import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import LoginButton from '@/components/LoginButton'
import { SignupButton } from '@/components/SignupButton'
import LogoutButton from '@/components/LogoutButton'
import Profile from '@/components/Profile'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            <a href="/protection">protection</a><br />
            <a href="/ssr">ssr</a><br />
            <a href="/users">users</a><br />
          </p>
          <div>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              className={styles.vercelLogo}
              width={100}
              height={24}
              priority
            />
          </div>
        </div>

        <div>
          <LoginButton />
          <br />
          <LogoutButton />
          <br />
          <SignupButton />
          <br />
          <Profile />
        </div>
      </main>
    </>
  )
}
